name: Check Changed Files
description: Check to see what type of files changed
outputs:
  is_angular_changed:
    description: Is this an Angular related changed?
    value: ${{ steps.check-angular-source.outputs.any_changed }}
  is_scully_changed:
    description: Is this a Scully related changed?
    value: ${{ steps.check-scully-source.outputs.any_changed }}
runs:
  using: "composite"
  steps:
    - name: Check out repo
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Check Angular Source
      id: check-angular-source
      uses: tj-actions/changed-files@v10
      with:
        files: |
          package.json
          nx.json
          workspace.json
          tailwind.config.js
          libs/**/*.*
          apps/**/*.*

    - name: Check Scully Source
      id: check-scully-source
      uses: tj-actions/changed-files@v10
      with:
        files: scully.ng-one-hundred.config.ts
