name: Build and Upload Artifacts
on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  check-files:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Check files changed
        uses: ./.github/actions/check-changed-files
        id: check-files-changed
    outputs:
      should_build: ${{ steps.check-files-changed.outputs.is_angular_changed == 'true' }}
  build:
    needs: check-files
    if: ${{ needs.check-files.outputs.should_build }}
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
        with:
          ref: main

      - name: Derive appropriate SHAs for base and head for `nx affected` commands
        uses: nrwl/nx-set-shas@v2

      - name: Cache node modules
        uses: actions/cache@v2
        id: cached-deps
        env:
          cache-name: cache-node-modules
        with:
          # npm cache files are stored in `~/.npm` on Linux/macOS
          path: '**/node_modules'
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - name: Setup NodeJS
        uses: actions/setup-node@v2

      - name: Install dependencies
        if: ${{ steps.cached-deps.outputs.cache-hit != 'true' }}
        run: yarn install

      - name: Download Nx Cache
        continue-on-error: true
        uses: dawidd6/action-download-artifact@v2
        with:
          name: ngvn-nx-cache
          workflow: build-and-upload-artifacts.yml

      - name: Build projects
        run: |
          if [ "${{ env.NX_BASE == '' || env.NX_BASE == null || env.NX_HEAD == '' || env.NX_HEAD == null }}" = "true" ];
          then
            yarn build
          else
            yarn build:affected
          fi

      - name: Upload Nx Cache
        uses: actions/upload-artifact@v2
        with:
          name: ngvn-nx-cache
          path: ./node_modules/.cache/nx

      - name: Upload Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: ngvn-artifacts
          path: |
            ./dist/apps
            ./dist/libs
