name: Build and Upload Artifacts
on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
        with:
          ref: main

      - name: Cache node modules
        uses: actions/cache@v2
        id: cached-deps
        env:
          cache-name: cache-node-modules
        with:
          # npm cache files are stored in `~/.npm` on Linux/macOS
          path: '**/node_modules'
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - name: Setup NodeJS
        uses: actions/setup-node@v2

      - name: Install dependencies
        if: ${{ steps.cached-deps.outputs.cache-hit != 'true' }}
        run: yarn install

      - name: Build projects
        run: yarn build --base-href=/100-day/

      - name: Upload Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: ngvn-artifacts
          path: |
            ./dist/apps
